sudo: required
services:
  - docker: 

before_install:
  - docker build -t dhirendrabyte/react-app -f Dockerfile.node .

script:
  - docker run -d dhirendrabyte/react-app npm run test -- --coverage
  - docker ps

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-travis1"
  env: "Dockertravis1-env"
  bucket_name: "elasticbeanstalk-ap-south-1-173402306626"
  bucket_path: "docker-travis1"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"