sudo: required
services:
  - docker: 

before_install:
  - docker build -t dhirendrabyte/react-node_app -f Dockerfile .

script:
  - docker run dhirendrabyte/react-node_app npm run test -- --coverage  
